### ISSUE TITLE
Can't get the video

### ISSUE THREAD

**Issue by shahishasank** [YehudaEi/Youtube-Downloader#1]
I'm getting this error
GET http://localhost:8080/YouTube/.mp4?url=https://www.youtube.com/watch?v=Q2J2TMsGcFI 404 (Not Found)
I'm using php v 7.3 with xampp server

**Comment by StorryTV** [comment]
Make sure port 8080 is available to talk outside the network if you use localhost by opening that port on your router and whitelisting it in any firewall on your Windows PC

P.S. I assume it's on your home network, because it's localhost on XAMPP (Windows based)

**Comment by YehudaEi** [comment]
@shahishasank 
I really really apologize for not answering until now, I suggest you make sure that the .htaccess file exists and works properly.

This is probably the problem.
